deploy:
  stage: deploy
  script:
    - echo "Deploying to VM..."
    - mkdir -p ~/.ssh
    - echo -e "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
    - chmod 600 ~/.ssh/id_ed25519
    - |
      ssh -t -i ~/.ssh/id_ed25519 wishjet49@34.57.1.13 -o StrictHostKeyChecking=no
        cd ~/todolist-app
        git pull origin main
        sudo docker-compose down
        sudo docker system prune -af
        sudo docker volume prune -f
        sudo docker-compose up --build -d
        sudo systemctl restart nginx
      EOF
  only:
    - main
