deploy:
  stage: deploy
  script:
    - echo "🚀 Deploying on GCP VM..."
    - cd /home/wishjet49/todolist-app  
    - git pull origin main
    - sudo docker-compose down
    - sudo docker-compose up --build -d
    - sudo systemctl restart nginx
  only:
    - main
