image: docker:latest  # ใช้ Docker ใน Runner

services:
  - docker:dind  # ใช้ Docker-in-Docker เพื่อรันคอนเทนเนอร์ใน Runner

stages:
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375 
  DOCKER_TLS_CERTDIR: ""

deploy:
  stage: deploy
  script:
    - echo "🚀 Deploying on GCP VM..."
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - docker pull my-docker-image:latest 
    - docker-compose down  
    - docker-compose up --build -d  
    - sudo systemctl restart nginx 
  only:
    - main
