stages:
  - build
  - deploy

variables:
  SSH_USER: "wishjet49"
  VM_HOST: "34.72.155.6"
  SSH_KEY: $SSH_PRIVATE_KEY # Set this in GitLab CI/CD variables

build:
  stage: build
  script:
    - echo "Building the project..."
    - docker-compose build
  only:
    - main

deploy:
  stage: deploy
  script:
    - echo "Deploying to VM..."
    - ssh $SSH_USER@$VM_HOST <<EOF
      cd ~/todolist-app
      git pull origin main
      docker-compose down
      docker-compose up --build -d
      EOF
  only:
    - main
